### ISSUE TITLE
How to connect via USB?

### ISSUE THREAD

**Issue by awaescher** [luchermans/el-tako_home#1]
**This is not an issue but a question**

Thanks for this repository in advance: I am currently trying to figure out how to read and write commands from and to Eltako devices.
Your repository is of great help so far. I am however at the very beginning with my Eltako experiments and am just trying to get signals from a FAM14 via USB.

Would you please please elaborate how you managed to connect to the FAM14 using the micro usb cable?

> Connect the FAM14 USB (virtual serial port)
> turn the FAM14 wheel BA to Pos. 4

Right now I connected the USB port but can't even find the USB device on my linux machine  😬

**Comment by luchermans** [comment]
BA wheel to pos 4 is only to get the status telegrams of the actuators
The USB driver is an FTDI see https://ftdichip.com/document/installation-guides/

I only send buttons and but it should be possible to send telegrams to activate set a relay/dimmer  see https://www.eltako.com/fileadmin/downloads/en/_main_catalogue/Gesamt-Katalog_ChT_gb_highRes.pdf ACTIVATION TELEGRAMS FROM THE GFVS SOFTWARE
I you figure out this please let me know.

ps. I'm using windows but it should work on Linux / Raspberry.
I think PCT14 only works on windows but it's not needed to operate.
Good luck   ;-)

**Comment by awaescher** [comment]
Thanks for your help :)

My idea was to connect PCT14 (on Windows) to maybe find available devices and ids/codes, etc. With this, I hoped to be able to extract all the information I need to emulate interactions without PCT14 later on.

Very helpful to learn about the FTDI. I will definitely check this out, however I have no access to the Eltako devices these days. I will definitely come back to this thread.
