### ISSUE TITLE
Where can I find the "data" from FCT14?

### ISSUE THREAD

**Issue by adaxi** [luchermans/el-tako_home#2]
First of all I would like to thank you for this project!

I have tried to use it, and even managed to control one of my switches. When I tried to control a second switch it had no effect.

I was wondering where you get the "data" value from PCT14 to be added to the `el-tako_home.json` file. Below you can find a couple of screenshots of what I am seeing in PCT14.

![Screenshot from 2023-01-21 23-08-11](https://user-images.githubusercontent.com/474682/213887494-e290d96a-419f-468f-8e52-415a8c086ca4.png)

![Screenshot from 2023-01-21 23-09-33](https://user-images.githubusercontent.com/474682/213887505-cb2bdaa9-28f9-43a7-acb6-38bb62f0e25e.png)

**Comment by luchermans** [comment]
Hi adaxi,

I've added [PCT14_2json.md](https://github.com/luchermans/el-tako_home/blob/main/PCT14_2json.md) (used your screenshot as an example).
If not correct or clear please let me know.

**Comment by adaxi** [comment]
I'll try it out next Friday, thank you for the explanation, I think I understand how to proceed.

**Comment by adaxi** [comment]
Works great!
